services:
  server:
    build:
      context: .
    volumes:
      - ./data/sqlite:/var/lib/kutt
      - ./custom:/kutt/custom
    container_name: kutt
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
      REDIS_ENABLED: true
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ENABLED: ${CORS_ENABLED}
      TRUST_PROXY: true
    ports:
      - 3000:3000
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - ${REDIS_PORT}

volumes: {}
