services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:15
    container_name: teleport
    restart: unless-stopped
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
