http:
  middlewares:
    # Redirect HTTP to HTTPS
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    
    # Add www prefix if missing
    redirect-to-www:
      redirectRegex:
        regex: "^https://example\\.com/(.*)"
        replacement: "https://www.example.com/${1}"
        permanent: true
        
    # Remove trailing slash
    strip-trailing-slash:
      redirectRegex:
        regex: "^(https?://[^/]+/[^/]+)/$"
        replacement: "${1}"
        permanent: true