http:
  middlewares:
    secure:
      headers:
        # Security-related headers
        stsSeconds: 31536000                        # 1 year
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        
        # Content security policies
        contentTypeNosniff: true
        browserXssFilter: true
        
        # Custom headers
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
          server: ""                               # Remove server info
          
        # Default referrer policy
        referrerPolicy: "strict-origin-when-cross-origin"
        
        # Content-Security-Policy
        contentSecurityPolicy: >-
          default-src 'self';
          img-src 'self' data:;
          style-src 'self' 'unsafe-inline';
          script-src 'self' 'unsafe-inline';
          connect-src 'self';
          frame-ancestors 'self';