services:
  caddy:
    image: caddy:2.7
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./headers:/etc/caddy/headers:ro
      - ./sites:/etc/caddy/sites:ro
      - ../cloudflare/origin:/certs:ro
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy-data:
  caddy-config:
