# Alertmanager configuration (sanitised)

global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram-notifier'

receivers:
  - name: telegram-notifier
    telegram_configs:
      - bot_token: REPLACE_ME_TELEGRAM_BOT_TOKEN
        chat_id: REPLACE_ME_CHAT_ID
        message_thread_id: REPLACE_ME_THREAD_ID
        parse_mode: HTML
        send_resolved: true
        message: '{{ template "telegram.default" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'critical'
