- name: Install prerequisite packages
  hosts: all
  vars:
    ansible_host_key_checking: false
  become: yes
  user: "{{ansible_user}}"
  tasks:    
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - curl
        - wget
      ignore_errors: yes 

    - name: Install other packages
      ansible.builtin.shell: wget -qO- https://bit.ly/tamld-server-apps | bash
      become: no
      ignore_errors: yes 