---
- name: Install prerequisite packages
  hosts: tlbb3d
  become: yes
  user: "{{ansible_user}}"

  tasks:    
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - curl
        - wget
        - nano
        - git
        - tmux
        - tree
        - neofetch
        - net-tools
        - unzip
        - jq
        - thefuck
      ignore_errors: yes 

    - block:
      - name: Install exa binary
        block:
          - name: Download exa binary zip
            get_url:
              url: https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip
              dest: /tmp/exa-linux-x86_64-v0.10.1.zip

          - name: Unzip the exa binary
            unarchive:
              src: /tmp/exa-linux-x86_64-v0.10.1.zip
              dest: /tmp/
              remote_src: yes

          - name: Move exa binary to /usr/local/bin
            command:
              cmd: mv /tmp/bin/exa /usr/local/bin/exa

          - name: Remove temporary files for exa installation
            file:
              path: "{{ item }}"
              state: absent
            loop:
              - /tmp/exa-linux-x86_64-v0.10.1.zip
              - /tmp/bin/

      - name: Install tmux configuration
        block:
          - name: Clone tmux repository
            git:
              repo: 'https://github.com/gpakosz/.tmux.git'
              dest: '~/.tmux'
              clone: yes
              update: yes

          - name: Create symbolic link to tmux.conf
            file:
              src: '~/.tmux/.tmux.conf'
              dest: '~/.tmux.conf'
              state: link

          - name: Copy tmux.conf.local file
            copy:
              src: '~/.tmux/.tmux.conf.local'
              dest: '~/.tmux.conf.local'
              remote_src: yes

    - name: Install ZSH shell and it's dependencies
      command: su -c -m "{{ ansible_user }}" "wget -qO- https://gist.githubusercontent.com/tamld/7be6595bbffe5f9812ee448569c2b09c/raw/install-zsh.sh | bash"
      ignore_errors: yes 
