# ================================
# Static configuration for Traefik
# ================================
# This file is loaded at container startup
# Used to define entry points, API, providers, TLS resolver, and logging

# Define network entry points (i.e., ports Traefik listens on)
entryPoints:
  web:
    address: ":80"            # HTTP port
  websecure:
    address: ":443"           # HTTPS port
  # wireguard:
  #   address: ":51820/udp"     # UDP Wireguard    

# Enable Traefik's internal dashboard
api:
  dashboard: true             # Enable web UI at /dashboard (secured via middleware)
  insecure: false             # Must be false to use dashboard securely via HTTPS + middleware

# Logging level (can be DEBUG, INFO, WARN, ERROR)
log:
  level: INFO

# Enable ACME certificate resolver via Cloudflare DNS challenge
certificatesResolvers:
  cloudflare:
    acme:
      email: "${CF_API_EMAIL}"       # Email for Let's Encrypt registration
      storage: acme.json             # File to store obtained certificates
      dnsChallenge:
        provider: cloudflare         # Use Cloudflare DNS API for domain validation
        resolvers:
          - "1.1.1.1:53"             # Cloudflare DNS
          - "8.8.8.8:53"             # Google DNS (backup)
        delayBeforeroot@pve:~/scripts# tree .
        
# Comment out static TLS certificate block to enable ACME certificate provisioning
# tls:
#   certificates:
#     - certFile: "/certs/cloudflare/origin.crt"
#       keyFile: "/certs/cloudflare/origin.key"

# Enable configuration from files (used for routers/services/middlewares)
providers:
  file:
    directory: /etc/traefik/dynamic  # Path mounted from host to store dynamic config files
    watch: true                      # Enable auto-reload when files change
  
  # Uncomment to enable Docker provider (auto-discovery of Docker containers)
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false   # Only expose containers with traefik.enable=true label